<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginAttachment extends BaseAttachment
{
  public function __toString()
  {
      return $this->name;
  }
	public function getObject()
	{
		return Doctrine::getTable($this->getObjectClass())->findOneById($this->getObjectId());
	}
	public function getDefaultFilepath()
	{
		sfLoader::loadHelpers('Url');
		return public_path($this->getUploadPath());
	}
	public function getUploadPath()
	{
		return sfConfig::get('sf_upload_dir').DIRECTORY_SEPARATOR.strtolower($this->getObjectClass()).DIRECTORY_SEPARATOR.$this->getUrl();
	}
	public function getAttachmentRoute()
	{
		return $this->getDefaultFilepath();
	}
}